#!/usr/bin/env node

const chalk = require('chalk')
const fs = require('fs')
const { exit } = require('process')

function countwords(file) {
  fs.readFile(file, { encoding: 'utf-8' }, (err, data) => {
    if (err) {
      console.log(chalk.red('ERROR', err))
    } else {
      console.log(
        chalk.green('Words in ' + file + ': ' + data.split(/\s/).length)
      )
    }
    exit(err ? 1 : 0)
  })
}

module.exports = countwords

countwords(process.argv[2])
