#!/usr/bin/env node

const fs = require('fs')

function countwords(file) {
  fs.readFile(file, { encoding: 'utf-8' }, (err, data) => {
    if (err) {
      console.log(chalk.red('ERROR', err))
    } else {
      console.log(
        chalk.green('Words in ' + file + ': ' + data.split(/\s/).length)
      )
    }
  })
}

module.exports = countwords

countwords(process.argv[2])
