#!/usr/bin/env node

const input = Number(process.argv[2])
const max = Number.isNaN(input) ? undefined : input
console.log(random(max))

function random(max = 10) {
  return Math.floor(Math.random() * (max + 1))
}
